config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :stores
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  belongs_to :store
  scope :by_store, lambda { |store| where(:store_id => store.id) }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_and_belongs_to_many :stores, :join_table => 'spree_products_stores'
  scope :by_store, lambda {|store| joins(:stores).where("spree_products_stores.store_id = ?", store)}
end

app/models/spree/store.rb
module Spree
  class Store < ActiveRecord::Base
    has_and_belongs_to_many :products, :join_table => 'spree_products_stores'
    has_many :taxonomies
    has_many :orders

    validates_presence_of :name, :code, :domains
    attr_accessible :name, :code, :default, :email, :domains

    scope :default, where(:default => true)
    scope :by_domain, lambda { |domain| where("domains like ?", "%#{domain}%") }

    def self.current(domain = nil)
      current_store = domain ? Store.by_domain(domain).first : nil
      current_store || first_found_default
    end

    def self.first_found_default
      @cached_default ||= Store.default.first
    end
  end
end

app/models/spree/taxonomy_decorator.rb
Spree::Taxonomy.class_eval do
  belongs_to :store
  attr_accessible :store_id
end

app/models/spree/tracker_decorator.rb
Spree::Tracker.class_eval do
  belongs_to :store

  def self.current(domain)
    Spree::Tracker.where(:active => true, :environment => ENV['RAILS_ENV']).joins(:store).where("spree_stores.domains LIKE '%#{domain}%'").first
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  update.before :set_stores

  private
  def set_stores
    @product.store_ids = nil unless params[:product].key? :store_ids
  end

end

app/controllers/spree/admin/stores_controller.rb
class Spree::Admin::StoresController < Spree::Admin::ResourceController

end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  before_filter :can_show_product, :only => :show

  private
  def can_show_product
    @product ||= Spree::Product.find_by_permalink!(params[:id])
    if @product.stores.empty? || @product.stores.include?(@site)
      render :file => "#{::Rails.root}/public/404.html", :status => 404
    end
  end

end

app/views/spree/admin/products/_index_headers.html.erb
<th><%= t("stores") %></th>

app/views/spree/admin/products/_index_rows.html.erb
<td><%= product.stores.map(&:code).join(", ") unless product.stores.empty? %></td>

app/views/spree/admin/products/_index_search_fields.html.erb
<p>
  <label><%= t("store") %></label><br />
  <%= f.select :stores_id_eq, Spree::Store.all.collect {|s| [s.name, s.id ] }, {:include_blank => true} %></p>
</p>

app/views/spree/admin/products/_stores.html.erb
<p>
  <%= f.label :stores, t("stores")%><br />
  <% Spree::Store.all.each do |store| %>
    <%= check_box_tag "product[store_ids][]", store.id, @product.stores.include?(store) %> <%= store.name %>
  <% end %>
</p>

app/views/spree/admin/stores/_form.html.erb
<table>
  <tr>
    <td><label><%=t("name")%></label></td>
    <td><%= text_field :store, :name, {"style" => "width:200px"} %></td>
  </tr>
  <tr>
    <td><label><%=t("code")%></label></td>
    <td><%= text_field :store, :code, {"style" => "width:50px"} %></td>
  </tr>
  <tr>
    <td><label><%= t("default") %></label></td>
    <td>
      <label class="sub">
        <%= radio_button(:store, :default, true ) %>
        <%= t("yes") %>
      </label> &nbsp;
      <label class="sub">
        <%= radio_button(:store, :default, false ) %>
        <%= t("no") %>
      </label>
    </td>
  </tr>
  <tr>
    <td><label><%=t("send_mails_as")%></label></td>
    <td><%= text_field :store, :email, {"style" => "width:200px"} %></td>
  </tr>
  <tr>
    <td><label><%=t("domains")%></label></td>
    <td><%= text_area :store, :domains, {:cols => 60, :rows => 4} %></td>
  </tr>
</table>

app/views/spree/admin/stores/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("editing_store") %></h1>
<%= render "spree/shared/error_messages", :target => @store %>
<%= form_for(@store, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("actions.cancel"), admin_stores_url %>
  </p>
<% end %>

app/views/spree/admin/stores/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_store"), new_object_url, :icon => 'add'  %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("stores") %></h1>

<table class="index">
  <thead>
    <th><%= t("name") %></th>
    <th><%= t("code") %></th>
    <th><%= t("send_mails_as") %></th>
    <th><%= t("domains") %></th>
    <th><%= t("action") %></th>
  </thead>
  <tbody>
    <% @stores.each do |store|%>
      <tr id="<%= dom_id store %>">
        <td width="120px"><%= store.name %></td>
        <td width="80px"><%= store.code %></td>
        <td width="80px"><%= store.email %></td>
        <td width="220"><%= store.domains %></td>
        <td width="140px">
          <%= link_to_edit store %> &nbsp;
          <%= link_to_delete store %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/stores/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("new_store") %></h1>
<%= render "spree/shared/error_messages", :target => @store %>

<%= form_for(:store, :url => collection_url) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons">
    <%= button t('continue') %>
    <%= t("or") %> <%= link_to t("actions.cancel"), admin_stores_url %>
  </p>
<% end %>

app/views/spree/admin/taxonomies/_form.html.erb
<div data-hook="admin_inside_taxonomy_form">
  <%= f.field_container :name do %>
    <%= f.label :name, t(:name) %> <span class="required">*</span><br />
    <%= error_message_on :taxonomy, :name, :class => 'fullwidth title'  %>
    <%= text_field :taxonomy, :name  %>
  <% end %>
</div>

<p>
  <%= f.label :name, t("store") %> <span class="required">*</span><br />
  <%= collection_select :taxonomy, :store_id, Spree::Store.all, :id, :name  %>
</p>

app/views/spree/admin/trackers/_index_rows.html.erb
<td><%=tracker.store.name %></td>

app/views/spree/admin/trackers/_store.html.erb
<tr>
  <td><label><%=t("store")%></label></td>
  <td>
    <%= collection_select(:tracker, :store_id, Spree::Store.all, :id, :name, {}) %>
  </td>
</tr>

app/views/spree/shared/_google_analytics.html.erb
<% if tracker = current_tracker %>

  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= tracker.analytics_id -%>']);
  _gaq.push(['_trackPageview']);
  
  <%- if flash[:commerce_tracking] -%>
  
  _gaq.push(['_addTrans',
    '<%= "#{"QA-" if request.server_name =~ /^(dev.|localhost)/ }#{@order.number}" %>', // order ID - required
    '<%= tracker.store.name -%>', // affiliation or store name
    '<%= @order.total -%>', // total - required
    '<%= @order.adjustments.tax.sum(:amount).to_s -%>', // tax
    '<%= @order.adjustments.shipping.sum(:amount).to_s -%>', // shipping
    '<%= @order.ship_address.city if @order.ship_address -%>', // city
    '<%= @order.ship_address.state.name if @order.ship_address and @order.ship_address.state -%>', // state or province
    '<%= @order.ship_address.country.name if @order.ship_address && @order.ship_address.country -%>' // country
  ]);

   <%- @order.line_items.each do |line_item| -%>
  _gaq.push(['_addItem',
    '<%= "#{"QA-" if request.server_name =~ /^(dev.|localhost)/ }#{@order.number}" %>', // order ID - required
    '<%= line_item.variant.sku -%>', // SKU/code - required
    '<%= line_item.variant.product.name -%>', // product name
    '-', // category or variation
    '<%= line_item.price -%>', // unit price - required
    '<%= line_item.quantity -%>' // quantity - required
  ]);
  <%- end -%>
  _gaq.push(['_trackTrans']); //submits transaction to the Analytics servers
  
  <%- end -%>
  
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
<% end %>